version: '3.8'
services:
  web:
    container_name: web
    build:
      context: ./.docker.prod/nginx
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80
    tty: true
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./.docker.prod/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    expose:
      - ${API_PORT}
    tty: true
    restart: always
