version: '3.8'
services:
  web:
    container_name: web
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80
    tty: true
    restart: always
    depends_on:
      - front

  front:
    container_name: front
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    environment:
      PORT: ${FRONT_PORT}
      HOST: '0.0.0.0'
    expose:
      - ${FRONT_PORT}
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: ${TZ}
      DB_CONNECTION: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SESSION_DOMAIN: 'localhost'
      SANCTUM_STATEFUL_DOMAINS: 'localhost'
      SESSION_DRIVER: 'cookie'
    volumes:
      - ./api:/app
    expose:
      - ${API_PORT}
    tty: true
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
          - db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always

volumes:
  db:
